<?php

/**
 * @file
 * Contains pyramid_content.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pyramid_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pyramid_content module.
    case 'help.page.pyramid_content':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides drush commands to import content') . '</p>';
      return $output;

    default:
  }
}
