name: pyramid
recipe: drupal8
services:
  appserver:
    webroot: web
    # ==========================
    # Enable XDebug
    # @see  https://docs.devwithlando.io/tutorials/lando-with-vscode.html 
    # @code sudo iptables -A INPUT -p tcp -d 0/0 --dport 9009 -j ACCEPT
    # ==========================
    # xdebug: true
    # config: 
    #  php: .vscode/php.ini    
  pma:
    type: phpmyadmin
    hosts:
      - database
  node:
    type: node
    build:
      - npm install
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
#
# ==========================
# Shortcode comands
# @code lando lando npm run watch
# ==========================
tooling:
  npm:
    service: node
  drush:
    cmd: ./bin/drush
#
# ==========================
# Custom domains
# @see lando info
# ==========================
proxy:
  pma:
    - pma.kline.lndo.site
  mailhog:
    - mail.kline.lndo.site
#  appserver:
#    - "yoursite.lndo.site"
#    - "*.yousite.lndo.site"
#
# ==========================
# Automation
# ==========================
events:
  post-start:
    - echo "=========================="
    - echo "Install"
    - echo "=========================="
    - appserver: "cd $LANDO_MOUNT/ && composer install -o"
    # ========================== REMOVE THIS PART AFTER FIRST INSTALL
    - echo ""
    - echo "=========================="
    - echo "First install from config"
    - echo "=========================="
    - appserver: "cd $LANDO_MOUNT/ && composer first-install"
    - appserver: "cd $LANDO_MOUNT/ && composer drush site-install config_installer -y"
    - appserver: "cd $LANDO_MOUNT/ && composer drush upwd admin admin"
    - appserver: "cd $LANDO_MOUNT/ && composer drush en pyramid_content"
    - appserver: "cd $LANDO_MOUNT/ && composer drush pmu pyramid_content default_content default_content_extra hal serialization"
    - echo ""
    - echo "=========================="
    - echo "Building theme assets..."
    - echo "=========================="
    - node: "cd $LANDO_MOUNT && npm install"
    - node: "cd $LANDO_MOUNT && npm run build"
    # ========================== REMOVE THIS PART AFTER FIRST INSTALL
    - echo ""
    - echo "=========================="
    - echo "Update database..."
    - echo "=========================="
    - appserver: "cd $LANDO_MOUNT/ && ./bin/drush cim -r web"
    - appserver: "cd $LANDO_MOUNT/ && ./bin/drush entup -r web"
    - appserver: "cd $LANDO_MOUNT/ && ./bin/drush updb -r web"
    - appserver: "cd $LANDO_MOUNT/ && ./bin/drush locale-update -r web"
    - appserver: "cd $LANDO_MOUNT/ && ./bin/drush cr -r web"
    - echo ""
    - echo "=========================="
    - echo "Building theme assets..."
    - echo "=========================="
    - node: "cd $LANDO_MOUNT && npm run build"
    - echo ""
    - echo "=========================="
    - echo "Doing code review..."
    - echo "=========================="
    - appserver: "cd $LANDO_MOUNT/ && composer code-review"
    - appserver: "cd $LANDO_MOUNT/ && composer run-tests"
    #- node: "cd $LANDO_MOUNT && npm run lint"
    #- node: "cd $LANDO_MOUNT && npm run stats"    
